=== YaxcheAl/Lema-Proyecto-Juan-Yaxche/schema/curriculum_juan.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="curriculum">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="informacion_personal">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="correo_electronico" type="xs:string" />
                            <xs:element name="telefono" type="xs:string" />
                            <xs:element name="direccion" type="xs:string" />
                            <xs:element name="fecha_nacimiento" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="resumen_profesional" type="xs:string" />
                <xs:element name="educacion">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="centro_educativo" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="Titulo_Grado" type="xs:string" />
                                        <xs:element name="Periodo" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="experiencia_laboral" type="xs:string" />
                <xs:element name="habilidades">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="habilidad" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== YaxcheAl/Lema-Proyecto-Juan-Yaxche/schema/curriculum_juan.xml
<curriculum xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="curriculum_juan.xsd">
    <informacion_personal>
        <nombre>Juan</nombre>
        <correo_electronico>juanandresmataz40@gmail.com</correo_electronico>
        <telefono>+34 631 63 52 36</telefono>
        <direccion>calle Diego martinez de alava 4, bajo b</direccion>
        <fecha_nacimiento>08/09/2006</fecha_nacimiento>
        <imagen>../imagenes/yo.jpg</imagen>
    </informacion_personal>
    <resumen_profesional>
        Estudiante de Administracion de Sistemas Informaticos y Redes sin experiencia, empecé desde cero en este mundo hace casi 1 año.
    </resumen_profesional>
    <educacion>
        <centro_educativo>
            <nombre>U.E NUESTRA SEÑORA DE LA ASUNCIÓN</nombre>
            <Titulo_Grado>Bachillerato</Titulo_Grado>
            <Periodo>2022-2023</Periodo>
        </centro_educativo>
        <centro_educativo>
            <nombre>Ciudad Jardin</nombre>
            <Titulo_Grado>Administracion de Sistemas Informaticos y Redes (primer año)</Titulo_Grado>
            <Periodo>2024-2025</Periodo>
        </centro_educativo>
    </educacion>
    <experiencia_laboral>

    </experiencia_laboral>
    <habilidades>
        <habilidad>Me adapto a casi todo</habilidad>
    </habilidades>
</curriculum>
